name: Publish main

on:
  push:
    branches:
      - main
      - ci/**

jobs:
  publish:
    uses: ./.github/workflows/publish-containers.yaml
    with:
      prefix: unstable-
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CLOUD_CI_WEBHOOK_URL }}
      SLACK_MENTION_GROUP_ID: ${{ secrets.SLACK_CORE_SUPPORT_GROUP_ID }}
